name: Analyse de sécurité Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t gestion_bancaire:latest .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.16.0
        with:
          image-ref: gestion_bancaire:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
